1) Создать матрицу numpy размером 3 на 2 на базе списка (2 способами).

In [6]:
import numpy as np
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(arr.shape)
arr2 = arr.reshape(3, 2)
print(arr2.shape)
arr3 = arr.reshape(1, 6)
print(arr3, arr3.shape)

arr = np.array([x for x in range(6)]).reshape(3,2)
print(arr)

(6,)
(3, 2)
[[1 2 3 4 5 6]] (1, 6)
[[0 1]
 [2 3]
 [4 5]]


1.1) При создании матрицы numpy передать целые значения, но сделать так, чтобы тип элементов массива был с плаваоющей точкой.

In [9]:
np.array([x for x in range(6)], dtype=np.float64).reshape(3,2)

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.]])

2) Из одномерного массива numpy из 10 элементов сделать: матрицу 5 на 2, матрицу 2 на 5, матрицу 10 на 1.

In [10]:
a = np.array([x for x in range(10)])
a.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

3) создать матрицу 3 на 4 состоящую из последовательно идущих четных значений.

In [14]:
#a = np.array([2*x for x in range(12)])
a = np.arange(0, 24, 2)
m = a.reshape(3, 4)
m

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

4) Из матрицы, полученной в задаче 3, выбрать подматрицу 2 на 2 состоящую из 4х верхних и левых элементов исходной матрицы.

In [21]:
m[:2, :2]

array([[ 0,  2],
       [ 8, 10]])

4.1) Создать квадратную матрицу 3 на 3 содержащую в правом нижнем угле подматрицу, полученную в задаче 4. На остальных местах должны находиться 0.

In [27]:
b = np.zeros((3,3))
print(b)
b[1:3, 1:3] = m[:2, :2]
b

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


array([[  0.,   0.,   0.],
       [  0.,   0.,   2.],
       [  0.,   8.,  10.]])

4.2) создать диаганальную матрицу 4 на 4 содержащую на главной диаганали значения из 1й (по индексу) строки матрицы из задачи 3. 

In [30]:
np.diag(m[1])

array([[ 8,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 12,  0],
       [ 0,  0,  0, 14]])

5) Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]] (решение без использования циклов!)

In [43]:
a = np.array(range(1, 8)).reshape(1, 7)
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [41]:
b = np.array(range(0,11)).reshape(11,1)
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [44]:
a + 10*b

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

6) Рассчитать значения квадратного уравнения: $$2x^2-x-5$$ 200 значений x в интервале от -5 до 5

In [49]:
x = np.linspace(-5, 5, 200)
y = 2 * x **2 - x - 5



7) Создать целочисленную невырожденную матрицу 4 на 4 (M), состоящую из случайных чисел, и целочисленный столбец 4 на 1 (a), состоящую из случайных чисел, с суммой значений больше 10 (проверить) и меньше 100. Найти y = M * a

In [62]:
M = np.tril(np.random.randint(0, 100, (4, 4)))
a = np.random.randint(3, 25, (4,1))
print(a)
y = np.dot(M, a)
y

[[ 4]
 [13]
 [23]
 [12]]


array([[ 380],
       [ 822],
       [3342],
       [2038]])

8) По значению y и M найти а 

In [63]:
# y = M * a
a = np.dot(np.linalg.inv(M), y)
a

array([[  4.],
       [ 13.],
       [ 23.],
       [ 12.]])

9) экспортировать матрицу M в эксель через формат CSV.

In [67]:
np.savetxt('export.csv', M, delimiter=';', fmt='%i')

10) Из массива, состоящего из 100 случайных чисел из интервала от 0 до 10 средствами numpy выбрать только те значения, которые находятся в интервале от 4.5 до 6.5 и вернуть их в виде массива numpy. 

In [75]:
a = np.random.uniform(0, 10, 100)
b = np.logical_and((a > 4.5),(a < 6.5))
a[b]

array([ 4.67599777,  6.41286137,  4.55820374,  5.23951754,  6.43259338,
        4.58224504,  6.22591842,  4.75161279,  5.23435985,  6.42832273,
        6.00086736,  5.73140314,  6.23886283,  4.5566928 ])

In [77]:
a = np.random.uniform(0, 10, 100)
a = a[a>4.5]
a = a[a<6.5]
a

array([ 4.82254518,  4.97250991,  4.58508131,  5.74557322,  5.13449471,
        5.81255854,  5.4475031 ,  5.00451725,  5.35308136,  6.24301702,
        5.96986338,  4.56977842,  4.76666308,  6.11903651,  6.22068168,
        6.03364567,  6.06726927,  5.10305129,  5.19980465,  5.48894328,
        6.26418342,  4.67551311,  4.51086737])

11) Создать целочисленную невырожденную матрицу M размерности 5 на 10, состоящую из случайных чисел. 
Средствами numpy выбрать из M столбец с максимальной суммой значений и вывести его на экран.
Средствами numpy выбрать из M строку с минимальной суммой значений и вывести ее на экран.