11) Создать целочисленную невырожденную матрицу M размерности 5 на 10, состоящую из случайных чисел. 
Средствами numpy выбрать из M столбец с максимальной суммой значений и вывести его на экран.
Средствами numpy выбрать из M строку с минимальной суммой значений и вывести ее на экран.

In [21]:
import numpy as np
M = np.random.randint(0, 10, (5, 10))
print(M)

[[8 9 5 2 1 2 6 8 4 1]
 [6 3 7 9 8 9 6 1 6 3]
 [9 7 1 5 8 8 6 6 7 6]
 [3 2 8 3 7 5 4 0 9 6]
 [4 2 8 9 0 4 8 2 9 6]]


In [22]:
M.sum(axis=0)

array([30, 23, 29, 28, 24, 28, 30, 17, 35, 22])

In [23]:
np.argmax(M.sum(axis=0))

8

In [27]:
print(M[:, np.argmax(M.prod(axis=0))])

[4 6 7 9 9]


In [25]:
print(M[np.argmin(M.sum(axis=1)), :])

[8 9 5 2 1 2 6 8 4 1]


3.	Создать иерархию классов для фруктов, продающихся в магазине. Иерархия должна содержать не менее 5 классов, и не менее 3х уровней. Объекты должны содержать не менее 3х атрибутов и 2х методов (часть из которых должны быть перегружены). В конструкторах должны корректно использоваться конструкторы базовых классов. Необходимо заполнить список представителями всех классов (всего не менее 10 объектов) и продемонстрировать работу полиморфизма.

In [72]:
# верхний класс - фрукты (1 атрибут, 1 метод)
# фрукты делятся на: цитрусовые + яблоки (по 1 атрибуту и 1 методу)
# цитрусовые делятся на: лимоны + апельсины (по 1 атрибуту)
import random
class Fruit(object):
    def __init__(self, color):
        self.color = color
        self.pealed = False
    def peal(self):
        self.pealed = True
    def cook(self):
        return 'cut fruit', 1
    def __str__(self):
        return "{}: {} ({})".format(self.__class__.__name__, self.color, 'pealed' if self.pealed else 'not pealed')
    
class Citrus(Fruit):
    def __init__(self, color):
        super().__init__(color)
        self.seeds = random.randint(0, 10)
        self.juiced = False
    def get_juice(self):
        assert not self.juiced, "Juice has already been made!"
        self.juiced = True
        return random.randint(1, 5)
    
class Apple(Fruit):
    def __init__(self, color, kind):
        super().__init__(color)
        self.kind = kind
    def cut(self, parts):
        print("Congrats! You cut the apple into {} pieces.".format(parts))
    def cook(self):
        return 'apple pie', 3
    
class Lemon(Citrus):
    def __init__(self):
        super().__init__('yellow')
    def cook(self):
        return 'lemon jam', 4
        
class Orange(Citrus):
    def __init__(self):
        super().__init__('orange')

class Basket():
    def __init__(self):
        self.contents = []
        self.__applecount = 0
        self.__lemoncount = 0
    
    @property
    def applecount(self):
        return self.__applecount
    
    @applecount.setter
    def applecount(self, x):
        self.__applecount = x
        
    @property
    def lemoncount(self):
        return self.__lemoncount
    
    @lemoncount.setter
    def lemoncount(self, x):
        self.__lemoncount = x
        
    @property
    def totalcount(self):
        return len(self.contents)
        
    def add_fruits(self, *fruits):
        self.contents += fruits
        for x in fruits:
            if isinstance(x, Apple): self.applecount += 1
            elif isinstance(x, Lemon): self.lemoncount += 1
    

In [58]:
c = Citrus('yellow')
c.pealed

False

In [59]:
lemon = Lemon()
print(lemon.color, lemon.seeds, lemon.get_juice(), lemon.pealed)

yellow 4 3 False


In [60]:
lemon.peal()
lemon.pealed

True

In [61]:
different_fruits = [Fruit('red'), Citrus('green'), Apple('pink', 'malinka'), Lemon(), Orange()]

In [62]:
for x in different_fruits:
    print("{} -> dish '{}', taste {}".format(x, *x.cook()))

Fruit: red (not pealed) -> dish 'cut fruit', taste 1
Citrus: green (not pealed) -> dish 'cut fruit', taste 1
Apple: pink (not pealed) -> dish 'apple pie', taste 3
Lemon: yellow (not pealed) -> dish 'lemon jam', taste 4
Orange: orange (not pealed) -> dish 'cut fruit', taste 1


In [63]:
lem = different_fruits[3]
lem.get_juice()

2

In [64]:
lem.get_juice()

AssertionError: Juice has already been made!

In [77]:
bs = Basket()

In [78]:
bs.add_fruits(Apple('green', 'antonovka'), Lemon(), Orange())
bs.contents

In [79]:
bs.totalcount

3

In [80]:
for x in bs.contents:
    print(x.cook())

('apple pie', 3)
('lemon jam', 4)
('cut fruit', 1)
