In [2]:
#1

In [9]:
#2
import numpy as np
def magic():
    a=np.array([0 for _ in range(100)]).reshape(10,10)
    it = np.nditer(a, op_flags=['readwrite'],flags=['c_index','multi_index'])
    while not it.finished:
        i=it.multi_index[0]
        j=it.multi_index[1]
        if j==i:
            it[0] = i+1
        it.iternext()
    return a
print(magic())

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [94]:
#3
import numpy as np
import random as r
a=np.array([r.randint(0, 9) for _ in range(30) ]).reshape(2,15)
b=np.array([r.randint(0, 9) for _ in range(15) ])
it = np.nditer([a[0],a[1],b], op_flags=['readwrite'],flags=['c_index','multi_index'])
print(a)
print(b)
#for x, y,z in np.nditer([a[0],a[1],b]):
 #   if x+y<z:
#      np.delete(a[0],x.index)
   #     np.delete(a[1],y.index)
    #print ("%d:%d:%d" % (x,y,z))
while not it.finished:
    i=it.multi_index[0]
    print("%d:%d:%d" %(it[0],it[1],it[2]))
    if(it[0]+it[1]<it[2]):
        np.delete(a,0,i)
        continue
    it.iternext()
print(a)
print(b)

[[6 4 9 1 9 8 2 8 7 8 2 6 4 5 2]
 [7 4 0 3 4 6 6 9 8 0 3 4 4 3 9]]
[3 4 2 6 8 1 6 2 1 3 5 5 2 6 2]
6:7:3
4:4:4
9:0:2
1:3:6


IndexError: tuple index out of range

In [91]:
import numpy as np
import random as r
a=np.array([r.randint(0, 9) for _ in range(30) ]).reshape(2,15)
print(a)
a=np.delete(a,0,1)
print(a)

[[4 7 0 1 3 3 8 9 5 5 8 5 8 3 3]
 [1 2 1 5 6 5 7 6 7 2 7 5 2 7 4]]
[[7 0 1 3 3 8 9 5 5 8 5 8 3 3]
 [2 1 5 6 5 7 6 7 2 7 5 2 7 4]]
