In [2]:
#1

In [9]:
#2
import numpy as np
def magic():
    a=np.array([0 for _ in range(100)]).reshape(10,10)
    it = np.nditer(a, op_flags=['readwrite'],flags=['c_index','multi_index'])
    while not it.finished:
        i=it.multi_index[0]
        j=it.multi_index[1]
        if j==i:
            it[0] = i+1
        it.iternext()
    return a
print(magic())

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [214]:
#3
import numpy as np
import random as r
a=np.array([r.randint(0, 9) for _ in range(30) ]).reshape(2,15)
b=np.array([r.randint(0, 9) for _ in range(15) ])
it = np.nditer([a[0],a[1],b], op_flags=['readwrite'],flags=['c_index'])
print(a)
print(b)
i=0
while not it.finished:
    if(it[0]+it[1]<it[2]):
        a=np.delete(a,i,1)
        i-=1
        print("deliting %d+%d<%d" %(it[0],it[1],it[2]))
    i+=1
    it.iternext()
print(a)

[[2 3 8 0 2 9 1 6 8 4 1 0 6 2 2]
 [0 8 8 6 3 7 3 8 3 7 6 2 7 6 0]]
[0 4 3 3 0 1 9 6 9 9 5 7 7 4 0]
deliting 1+3<9
deliting 0+2<7
[[2 3 8 0 2 9 6 8 4 1 6 2 2]
 [0 8 8 6 3 7 8 3 7 6 7 6 0]]
