In [ ]:
#1.1
class Binary_Tree_LI(object):
    
    @classmethod
    def check_list_validity(cls,lis):
        if len(lis)!=3:
            raise AssertionError("Недопустимый формат аргумента-списка")
        else:
            to_check = [l for l in lis[1:] if l!=[]]
            for elem in to_check:
                cls.check_list_validity(elem)
        
    
    def __init__(self, new_tree):
        if isinstance(new_tree, Binary_Tree_LI):
            self.tree = new_tree.get_tree_list()
        elif isinstance(new_tree, list):
            Binary_Tree_LI.check_list_validity(new_tree)
            self.tree = new_tree
        else:
            self.tree = [new_tree,[],[]]
            
    def __getitem__(self, position):
        return self.tree[position]
    
    def __setitem__(self, position,item):
        if position==0:
            self.tree[position] = item
        else:
            self.tree[position] = Binary_Tree_LI(item)
            
    def get_tree_list(self, do_print = False):
        if do_print:
            print(self.tree)
        return self.tree
    
    def get_left_child(self):
        return Binary_Tree_LI(self[1]) if len(self[1])==3 else None
    
    def get_right_child(self):
        return Binary_Tree_LI(self[2]) if len(self[2])==3 else None
    
    def get_val(self):
        return self[0]
    
    def set_val(self, new_val):
        self[0] = new_val
        
    def insert_left_child(self, node):
        self[1] = node
        
    def insert_left_child(self, node):
        self[2] = node
        

import operator
ops = {"+" : operator.add, "-" : operator.sub, "*": operator.mul}

def is_int(arg):
    try:
        int(arg)
        return True
    except:
        return False

def calculate(node):
    left_child = node.get_left_child()
    right_child = node.get_right_child()
    left_val = left_child.get_val()
    right_val = right_child.get_val()
    f = ops[node.get_val()]
    if is_int(left_val) and is_int(right_val):
        return ops[node.get_val()](left_val,right_val)
    elif is_int(left_val):
        return f(left_val, calculate(right_child))
    elif is_int(right_val):
        return f(calculate(left_child), right_val)
    else:
        return f(calculate(left_child), calculate(right_child))
        
tree = Binary_Tree_LI(["+",["-",[2,[],[]],[3,[],[]]],[1,[],[]]])
tree2 = Binary_Tree_LI(["-",["+",[4,[],[]],["*",[2,[],[]],[3,[],[]]]],[1,[],[]]])
print(calculate(tree))
print(calculate(tree2))

In [1]:
#1.2
import numpy as np
def morph(matrix):
    M = np.zeros((len(matrix),len(matrix[0])))
    M[1::2,::2] = 1
    M[::2,1::2] = 1
    return M

morph(np.arange(12).reshape(3,4))

array([[ 0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.]])

In [2]:
#1.3
M = np.fromfunction(lambda i,j : 3*i + 4*j + 2, (3,4))
print(M)

[[  2.   6.  10.  14.]
 [  5.   9.  13.  17.]
 [  8.  12.  16.  20.]]


In [25]:
#2.1
import random
def gen_list():
    length = random.randint(5,10)
    last = 0
    lis = []
    for i in range(length):
        lis.append(last)
        last+=random.randint(1,10)
    return lis


class Node(object):
    
    def __init__(self, val):
        self.value = val
        self.left_child = None
        self.right_child = None

class Binary_Search_Tree(object):
    
    def __init__(self, val):
        self.root = Node(val)
    
    def insert(self,val):
        to_insert = Node(val)
        pointer = self.root
        while(True):
            if to_insert.value > pointer.value:
                if pointer.right_child is None:
                    pointer.right_child = to_insert
                    return
                else:
                    pointer = pointer.right_child
            elif to_insert.value < pointer.value:
                if pointer.left_child is None:
                    pointer.left_child = to_insert
                    return
                else:
                    pointer = pointer.left_child
                    
    def display_tree(self):
        
        print(self.root.value)
        
        def display(node):
            if node is None:
                return
            if node.left_child is not None:
                print(node.left_child.value)
            if node.right_child is not None:
                print(node.right_child.value)
            display(node.left_child)
            display(node.right_child)
                
        display(self.root)

#Тестовые данные   
tree = Binary_Search_Tree(10)
tree.insert(7)
tree.insert(15)
tree.insert(3)
tree.insert(8)
tree.insert(13)
tree.insert(19)
#tree.display_tree()

def convert(lis):
    
    middle = len(lis)//2
    tree = Binary_Search_Tree(lis[middle])
    
    def convert_inner(lis, tree):
        if len(lis)<1:
            return
        elif len(lis)==1:
            tree.insert(lis[0])
            return
        middle = len(lis)//2
        tree.insert(lis[middle])
        convert_inner(lis[:middle],tree)
        convert_inner(lis[middle+1:],tree)
    
    convert_inner(lis[:middle],tree)
    convert_inner(lis[middle+1:],tree)
    return tree

tr = convert([1,3,4,5,7,9,10,12])
tr.display_tree()

7
4
10
3
5
1
9
12


In [3]:
#2.2
M = np.diag(np.arange(1,11))
rm = np.linalg.inv(M)
print(rm)
print(rm*M) #Проверка

[[ 1.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.5         0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.33333333  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.25        0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.2         0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.16666667
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.14285714  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.125       0.          0.        ]
 [ 0.          0.          0.          0.          0.   

In [ ]:
#2.3
matrix = np.random.randint(0,10,(2,15))
vector = np.random.randint(0,10,(1,15))
print(matrix)
print(vector)

In [ ]:
matrix2 = matrix.sum(axis=0)
filt = matrix2>vector
filt = filt & np.array([True,True]).reshape(2,1)
filt

In [ ]:
matrix[filt].reshape(2, len(matrix[filt])//2)